name: Build Staging

on:
  push:
    branches:
      - staging

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t ${{ github.repository }}:staging -f ./build/docker/Dockerfile --build-arg APP_MODE="debug" --no-cache .

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:staging